-- Migration 001: Initial Schema for Al Marakish Library Management System

-- 1. Admin Table
CREATE TABLE IF NOT EXISTS admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'admin',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    email VARCHAR(255),
    phone VARCHAR(50),
    position VARCHAR(100),
    profile_photo VARCHAR(255),
    permissions JSONB,
    ip_whitelist VARCHAR(255),
    last_login TIMESTAMPTZ,
    locked_until TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Users (Students & Members) Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_no VARCHAR(100) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    contact VARCHAR(100),
    date_of_birth DATE,
    address TEXT,
    blood_group VARCHAR(20),
    section VARCHAR(100),
    class VARCHAR(100),
    profile_photo VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    user_type VARCHAR(50) NOT NULL DEFAULT 'student',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Books Table
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_number VARCHAR(100),
    accession_number VARCHAR(100) UNIQUE,
    accession_no VARCHAR(100),
    barcode VARCHAR(100),
    isbn VARCHAR(100),
    title VARCHAR(500) NOT NULL,
    author VARCHAR(500),
    category VARCHAR(150) DEFAULT 'General',
    language VARCHAR(100) DEFAULT 'English',
    publisher VARCHAR(255),
    publication_year VARCHAR(50),
    edition VARCHAR(100),
    volume VARCHAR(100),
    pages INTEGER,
    price NUMERIC(10,2) DEFAULT 0.00,
    count INTEGER DEFAULT 1,
    copies INTEGER DEFAULT 1,
    location VARCHAR(150),
    description TEXT,
    call_number VARCHAR(100),
    call_no VARCHAR(100),
    cover_image VARCHAR(255),
    ebook VARCHAR(255),
    status VARCHAR(50) DEFAULT 'Available',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE RESTRICT,
    borrow_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    status VARCHAR(50) NOT NULL DEFAULT 'Borrowed',
    fine NUMERIC(10,2) DEFAULT 0.00,
    fine_paid NUMERIC(10,2) DEFAULT 0.00,
    fine_status VARCHAR(50) DEFAULT 'None',
    paid_at TIMESTAMPTZ,
    renewed INTEGER DEFAULT 0,
    notes TEXT,
    issued_by_admin_id BIGINT,
    issued_by_admin_name VARCHAR(255),
    issued_by_role VARCHAR(50),
    issued_ip VARCHAR(50) DEFAULT '0.0.0.0',
    action_source VARCHAR(100) DEFAULT 'manual',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. Fines Table
CREATE TABLE IF NOT EXISTS fines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id BIGINT REFERENCES books(id) ON DELETE SET NULL,
    transaction_id BIGINT REFERENCES transactions(id) ON DELETE SET NULL,
    amount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    amount_paid NUMERIC(10,2) DEFAULT 0.00,
    reason VARCHAR(255) DEFAULT 'Overdue',
    status VARCHAR(50) DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 6. Custom Fines Table
CREATE TABLE IF NOT EXISTS custom_fines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id BIGINT REFERENCES books(id) ON DELETE SET NULL,
    transaction_id BIGINT REFERENCES transactions(id) ON DELETE SET NULL,
    fine_type VARCHAR(100) NOT NULL,
    fine_amount NUMERIC(10,2) NOT NULL,
    reason TEXT NOT NULL,
    admin_remarks TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'pending_approval',
    created_by BIGINT REFERENCES admin(id) ON DELETE SET NULL,
    reviewed_by BIGINT REFERENCES admin(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    review_remarks TEXT,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. Custom Fines History Table
CREATE TABLE IF NOT EXISTS custom_fines_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fine_id BIGINT NOT NULL,
    action VARCHAR(100) NOT NULL,
    changed_by BIGINT,
    old_status VARCHAR(50),
    new_status VARCHAR(50),
    remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 8. Fine Payments Table
CREATE TABLE IF NOT EXISTS fine_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    transaction_id BIGINT REFERENCES transactions(id) ON DELETE SET NULL,
    fine_id BIGINT REFERENCES custom_fines(id) ON DELETE SET NULL,
    amount NUMERIC(10,2) NOT NULL,
    payment_method VARCHAR(50) DEFAULT 'upi',
    payment_reference VARCHAR(255),
    payment_screenshot VARCHAR(255),
    is_screenshot_requested SMALLINT DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    reviewed_by BIGINT REFERENCES admin(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    admin_remarks TEXT,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 9. Borrow Requests Table
CREATE TABLE IF NOT EXISTS borrow_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    request_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    transaction_id BIGINT REFERENCES transactions(id) ON DELETE SET NULL,
    processed_at TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 10. Student Registrations Table
CREATE TABLE IF NOT EXISTS student_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_no VARCHAR(100) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    date_of_birth DATE,
    address TEXT,
    contact VARCHAR(100),
    blood_group VARCHAR(20),
    section VARCHAR(100),
    password VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    rejection_reason TEXT,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 11. Reservations Table
CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    reservation_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ready_date DATE,
    expiration_date DATE,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 12. Book Suggestions Table
CREATE TABLE IF NOT EXISTS book_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(500) NOT NULL,
    author VARCHAR(500),
    category VARCHAR(150),
    description TEXT,
    reason TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    admin_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 13. Announcements Table
CREATE TABLE IF NOT EXISTS announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    message TEXT NOT NULL,
    target_role VARCHAR(50) NOT NULL DEFAULT 'all',
    created_by BIGINT,
    expires_at DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 14. User Notifications Table
CREATE TABLE IF NOT EXISTS user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(500) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) DEFAULT 'info',
    is_read BOOLEAN DEFAULT FALSE,
    link VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 15. Legacy Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(500) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) DEFAULT 'info',
    is_read BOOLEAN DEFAULT FALSE,
    status VARCHAR(50) DEFAULT 'unread',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 16. Activity Logs Table
CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    user_name VARCHAR(255),
    user_type VARCHAR(50) DEFAULT 'admin',
    user_role VARCHAR(50),
    action_type VARCHAR(100) NOT NULL,
    action_category VARCHAR(100) DEFAULT 'general',
    target_id BIGINT,
    target_type VARCHAR(100),
    target_name VARCHAR(500),
    action_description TEXT,
    metadata JSONB,
    ip_address VARCHAR(50),
    user_agent TEXT,
    status VARCHAR(50) DEFAULT 'success',
    severity VARCHAR(50) DEFAULT 'low',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 17. Admin Activity Logs (Legacy Table)
CREATE TABLE IF NOT EXISTS admin_activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL,
    admin_name VARCHAR(255),
    action_type VARCHAR(100) NOT NULL,
    action_description TEXT,
    related_table VARCHAR(100),
    related_id BIGINT,
    metadata TEXT,
    ip_address VARCHAR(50),
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 18. Book Issue Audit Table
CREATE TABLE IF NOT EXISTS book_issue_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT,
    book_id BIGINT,
    user_id BIGINT,
    admin_id BIGINT,
    action_type VARCHAR(50) NOT NULL DEFAULT 'issue',
    action_source VARCHAR(100) NOT NULL DEFAULT 'manual',
    book_title VARCHAR(500),
    accession_number VARCHAR(100),
    book_isbn VARCHAR(100),
    student_name VARCHAR(255),
    student_ad_no VARCHAR(100),
    admin_name VARCHAR(255),
    admin_role VARCHAR(50),
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_date DATE,
    returned_at TIMESTAMPTZ,
    ip_address VARCHAR(50) DEFAULT '0.0.0.0',
    user_agent TEXT,
    notes TEXT,
    current_status VARCHAR(50) DEFAULT 'Borrowed',
    is_rolled_back SMALLINT NOT NULL DEFAULT 0
);

-- 19. Security Logs Table
CREATE TABLE IF NOT EXISTS security_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    description TEXT,
    ip_address VARCHAR(50),
    user_agent TEXT,
    severity VARCHAR(50) DEFAULT 'medium',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 20. System Backups Table
CREATE TABLE IF NOT EXISTS system_backups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_name VARCHAR(255) NOT NULL,
    backup_type VARCHAR(50) DEFAULT 'manual',
    file_path VARCHAR(500),
    file_size BIGINT DEFAULT 0,
    status VARCHAR(50) DEFAULT 'completed',
    created_by BIGINT REFERENCES admin(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 21. Permissions Table
CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_key VARCHAR(100) NOT NULL UNIQUE,
    permission_name VARCHAR(255) NOT NULL,
    category VARCHAR(100) DEFAULT 'general',
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 22. Role Permissions Table
CREATE TABLE IF NOT EXISTS role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(50) NOT NULL,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_role_permission UNIQUE (role, permission_id)
);

-- 23. System Settings Table
CREATE TABLE IF NOT EXISTS system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(100) NOT NULL DEFAULT 'general',
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT,
    data_type VARCHAR(50) DEFAULT 'string',
    setting_type VARCHAR(50) DEFAULT 'string',
    setting_group VARCHAR(100) DEFAULT 'general',
    description TEXT,
    is_owner_only SMALLINT DEFAULT 0,
    can_edit_role VARCHAR(50) DEFAULT 'owner',
    updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 24. Settings (Legacy / Alias) Table
CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT,
    setting_group VARCHAR(100) DEFAULT 'general',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 25. System Settings History Table
CREATE TABLE IF NOT EXISTS system_settings_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL,
    old_value TEXT,
    new_value TEXT,
    changed_by BIGINT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 26. Approval Requests Table
CREATE TABLE IF NOT EXISTS approval_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type VARCHAR(100) NOT NULL,
    request_data JSONB,
    requested_by BIGINT,
    status VARCHAR(50) DEFAULT 'pending',
    reviewed_by BIGINT,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 27. Bulk Upload Audit Table
CREATE TABLE IF NOT EXISTS bulk_upload_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_type VARCHAR(100) NOT NULL,
    file_name VARCHAR(255),
    total_rows INTEGER DEFAULT 0,
    success_count INTEGER DEFAULT 0,
    failed_count INTEGER DEFAULT 0,
    uploaded_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 28. Bulk Upload Details Table
CREATE TABLE IF NOT EXISTS bulk_upload_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id BIGINT NOT NULL REFERENCES bulk_upload_audit(id) ON DELETE CASCADE,
    row_number INTEGER,
    identifier VARCHAR(255),
    status VARCHAR(50) DEFAULT 'success',
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 29. Failed Emails Table
CREATE TABLE IF NOT EXISTS failed_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient VARCHAR(255) NOT NULL,
    subject VARCHAR(500),
    body TEXT,
    error_message TEXT,
    retry_count INTEGER DEFAULT 0,
    status VARCHAR(50) DEFAULT 'failed',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 30. OPAC Popular Books Table
CREATE TABLE IF NOT EXISTS opac_popular_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    view_count INTEGER DEFAULT 0,
    borrow_count INTEGER DEFAULT 0,
    last_activity TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 31. OPAC Popular Searches Table
CREATE TABLE IF NOT EXISTS opac_popular_searches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_term VARCHAR(255) NOT NULL,
    search_count INTEGER DEFAULT 1,
    last_searched TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 32. OPAC Recent Views Table
CREATE TABLE IF NOT EXISTS opac_recent_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    ip_address VARCHAR(50),
    user_agent TEXT,
    viewed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 33. OPAC Search Analytics Table
CREATE TABLE IF NOT EXISTS opac_search_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query VARCHAR(500) NOT NULL,
    results_count INTEGER DEFAULT 0,
    ip_address VARCHAR(50),
    searched_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
